### ISSUE TITLE
covid19-world-map

### ISSUE THREAD

**Issue by raid21** [tedirghazali/codetube#4]
the data in covid19-world-map in index.js are static it was given, can you please make it dynamic by using an ipa because i tried to do it but i couldn't !

**Comment by tedirghazali** [comment]
Absolutely, right now I'm making timeline of covid19 with world map like
wikipedia projection

Pada tanggal Rab, 22 Apr 2020 01.59, Raid Boulahdid <
notifications@github.com> menulis:

**Comment by raid21** [comment]
Here is my index.js file i tried to make some modification in code to fit with an ipa but it doesn't dipslay the data on the web page, feel free to read it and execute it to understand.

[https://github.com/raid21/covid-map/blob/master/dataset-t.js](url)

**Comment by tedirghazali** [comment]
You have to download mapael and raphael js plugins first, and then extract
it to asset folder, get that plugin from this link
github.com/neveldo/jQuery-Mapael also, use cdn instead, either jsdelivr or
cdnjs, I have been seeing your project html and I found out your html file
is missing the mapael plugin

Pada tanggal Rab, 22 Apr 2020 15.52, Raid Boulahdid <
notifications@github.com> menulis:

**Comment by raid21** [comment]
I know and i did that it's just i didn't upload the full project, and i already integrated the mapael plugin using:  <script src="asset/mapael/jquery.mapael.js"></script>
i did everything and i don't get the result, here is the full project:

https://github.com/raid21/covid-map

**Comment by tedirghazali** [comment]
Also, you have to import its dependency, raphael.js, without this plugin,
mapael won't work, import jquery mousewheel too, I will see your project
again tomorow

Pada tanggal Rab, 22 Apr 2020 18.40, Raid Boulahdid <
notifications@github.com> menulis:

**Comment by tedirghazali** [comment]
I already fork, edit and pull request your project, please merge it, I
replace fetch with ajax, the problem is promise still pending when using
async and await

Pada tanggal Rab, 22 Apr 2020 21.28, Tedir Ghazali <tedirghazali@gmail.com>
menulis:

**Comment by raid21** [comment]
It's done, now it's working fine. i had to use ajax and set additional param async to false to use the data outside the request.

https://github.com/raid21/covid-cases-world-map

**Comment by raid21** [comment]
Ğ
