### ISSUE TITLE
Could you update the dark mode? 

### ISSUE THREAD

**Issue by fomundifr** [tedirghazali/codetube#7]
Could you update the dark mode by adding all the bootstrap components, since I am making a project and I need with the components and it does not work for me.

Would you be so kind to do it please.

**Comment by tedirghazali** [comment]
okay, this can take some time but I will provide other repo with bootstrap
5 components

Pada tanggal Sab, 22 Jan 2022 pukul 02.33 Fomundi ***@***.***>
menulis:
